# Generated by Django 5.1.7 on 2025-04-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, unique=True)),
                ("translated_text", models.CharField(max_length=255)),
                ("count", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
